class Stock {
  String symbol;
  /* String name; */
  String companyName;
  /* String description;
  String website;
  String region; */
  double price;
  double changePercent;

  Stock(
    this.symbol,
    /* this.name, */
    this.companyName,
    /* this.description,
    this.website,
    this.region, */
    this.price,
    this.changePercent,
  );

  @override
  toString() =>
      "Stock: {symbol: $symbol, companyName: $companyName, price: $price, changePercent: $changePercent}";
}

final List<Stock> stocks = _stocks
    .map((s) =>
        Stock(s["symbol"], s["companyName"], s["price"], s["changePercent"]))
    .toList(growable: false);

final List<Map<String, Object>> _stocks = [
  {
    "symbol": "BIAS",
    "companyName": "Boticario Intancia Análise Saudável",
    "price": "7.90",
    "changePercent": "3.0"
  },
  {
    "symbol": "BIAS",
    "companyName": "Boticario Intancia Análise Saudável",
    "price": "7.90",
    "changePercent": "3.0"
  },
  {
    "symbol": "BIAS",
    "companyName": "Boticario Intancia Análise Saudável",
    "price": "7.90",
    "changePercent": "3.0"
  },
  {
    "symbol": "BIAS",
    "companyName": "Boticario Intancia Análise Saudável",
    "price": "7.90",
    "changePercent": "3.0"
  },
];

class StockTitle {
  String symbol;
  String companyName;

  StockTitle(
    this.symbol,
    this.companyName,
  );

  @override
  toString() => "StockTitle: {symbol: $symbol, companyName: $companyName}";

  factory StockTitle.fromJson(Map<String, dynamic> parsedJson) {
    return StockTitle(
      parsedJson['symbol'],
      parsedJson['companyName'],
    );
  }
}

final List<StockTitle> allStockTitles = _allStocks
    .map((s) =>
        StockTitle(s["symbol"], s["companyName"]))
    .toList(growable: false);

final List<Map<String, Object>> _allStocks = [
  {"companyName":"3 R Petroleum", "symbol":"RRRP3"},
{"companyName":"Aco Altona", "symbol":"EALT3"},
{"companyName":"Aco Altona", "symbol":"EALT4"},
{"companyName":"Advanced Dh", "symbol":"ADHM3"},
{"companyName":"Aeris", "symbol":"AERI3"},
{"companyName":"Aes Tiete E", "symbol":"TIET11"},
{"companyName":"Aes Tiete E", "symbol":"TIET3"},
{"companyName":"Aes Tiete E", "symbol":"TIET4"},
{"companyName":"Afluente T", "symbol":"AFLT3"},
{"companyName":"Alfa Consorc", "symbol":"BRGE11"},
{"companyName":"Alfa Consorc", "symbol":"BRGE12"},
{"companyName":"Alfa Consorc", "symbol":"BRGE3"},
{"companyName":"Alfa Consorc", "symbol":"BRGE5"},
{"companyName":"Alfa Consorc", "symbol":"BRGE6"},
{"companyName":"Alfa Consorc", "symbol":"BRGE7"},
{"companyName":"Alfa Consorc", "symbol":"BRGE8"},
{"companyName":"Alfa Financ", "symbol":"CRIV3"},
{"companyName":"Alfa Financ", "symbol":"CRIV4"},
{"companyName":"Alfa Holding", "symbol":"RPAD3"},
{"companyName":"Alfa Holding", "symbol":"RPAD5"},
{"companyName":"Alfa Holding", "symbol":"RPAD6"},
{"companyName":"Alfa Invest", "symbol":"BRIV3"},
{"companyName":"Alfa Invest", "symbol":"BRIV4"},
{"companyName":"Alianscsonae", "symbol":"ALSO3"},
{"companyName":"Alianza Trust Renda Imobiliaria Fundo Investimento Imobiliario", "symbol":"ALZR11"},
{"companyName":"Alliar", "symbol":"AALR3"},
{"companyName":"Alpargatas", "symbol":"ALPA3"},
{"companyName":"Alpargatas", "symbol":"ALPA4"},
{"companyName":"Alper S.A.", "symbol":"APER3"},
{"companyName":"Alupar", "symbol":"ALUP11"},
{"companyName":"Alupar", "symbol":"ALUP3"},
{"companyName":"Alupar", "symbol":"ALUP4"},
{"companyName":"Amazonia", "symbol":"BAZA3"},
{"companyName":"Ambev S.A.", "symbol":"ABEV3"},
{"companyName":"Ambipar", "symbol":"AMBP3"},
{"companyName":"Ampla Energ", "symbol":"CBEE3"},
{"companyName":"Anima", "symbol":"ANIM3"},
{"companyName":"Arezzo Indústria e Comércio S.A.", "symbol":"ARZZ3"},
{"companyName":"AtmaSA", "symbol":"ATMP3"},
{"companyName":"Atompar", "symbol":"ATOM3"},
{"companyName":"Aura 360", "symbol":"AURA33"},
{"companyName":"Azevedo", "symbol":"AZEV3"},
{"companyName":"Azevedo", "symbol":"AZEV4"},
{"companyName":"Azul S.A.", "symbol":"AZUL4"},
{"companyName":"B2W", "symbol":"Companhia Digital"},
{"companyName":"B3 S.A.", "symbol":"Brasil, Bolsa, Balcão"},
{"companyName":"Bahema", "symbol":"BAHI3"},
{"companyName":"Banco Bmg", "symbol":"BMGB4"},
{"companyName":"Banco Bradesco S.A.", "symbol":"BBDC3"},
{"companyName":"Banco Bradesco S.A.", "symbol":"BBDC4"},
{"companyName":"Banco do Brasil S.A.", "symbol":"BBAS3"},
{"companyName":"Banco do Estado do Rio Grande do Sul S.A.", "symbol":"BRSR6"},
{"companyName":"Banco Inter", "symbol":"BIDI11"},
{"companyName":"Banco Inter S.A.", "symbol":"BIDI4"},
{"companyName":"Banco Inter S.A.", "symbol":"BIDI3"},
{"companyName":"Banco Pan", "symbol":"BPAN4"},
{"companyName":"Banco Santander (Brasil) S.A.", "symbol":"SANB3"},
{"companyName":"Banco Santander (Brasil) S.A.", "symbol":"SANB11"},
{"companyName":"Banese", "symbol":"BGIP3"},
{"companyName":"Banese", "symbol":"BGIP4"},
{"companyName":"Banestes", "symbol":"BEES3"},
{"companyName":"Banestes", "symbol":"BEES4"},
{"companyName":"Banpara", "symbol":"BPAR3"},
{"companyName":"Banrisul", "symbol":"BRSR3"},
{"companyName":"Banrisul", "symbol":"BRSR5"},
{"companyName":"Bardella", "symbol":"BDLL3"},
{"companyName":"Bardella", "symbol":"BDLL4"},
{"companyName":"Battistella", "symbol":"BTTL3"},
{"companyName":"Baumer", "symbol":"BALM3"},
{"companyName":"Baumer", "symbol":"BALM4"},
{"companyName":"BB Progressivo II Fundo de Investimento Imobiliario", "symbol":"FII"},
{"companyName":"BB Seguridade Participações S.A.", "symbol":"BBSE3"},
{"companyName":"Bic Monark", "symbol":"BMKS3"},
{"companyName":"Biomm", "symbol":"BIOM3"},
{"companyName":"Biosev", "symbol":"BSEV3"},
{"companyName":"Bk Brasil", "symbol":"BKBR3"},
{"companyName":"Boa Vista", "symbol":"BOAS3"},
{"companyName":"Bombril", "symbol":"BOBR3"},
{"companyName":"Bombril", "symbol":"BOBR4"},
{"companyName":"Br Brokers", "symbol":"BBRK3"},
{"companyName":"BR Malls Participações S.A.", "symbol":"BRML3"},
{"companyName":"Br Propert", "symbol":"BRPR3"},
{"companyName":"Bradespar S.A.", "symbol":"BRAP4"},
{"companyName":"Bradespar S.A.", "symbol":"BRAP3"},
{"companyName":"Brasilagro", "symbol":"AGRO3"},
{"companyName":"Braskem", "symbol":"BRKM6"},
{"companyName":"Braskem S.A.", "symbol":"BRKM5"},
{"companyName":"Braskem S.A.", "symbol":"BRKM3"},
{"companyName":"Brb Banco", "symbol":"BSLI3"},
{"companyName":"Brb Banco", "symbol":"BSLI4"},
{"companyName":"BRF S.A.", "symbol":"BRFS3"},
{"companyName":"Btgp Banco", "symbol":"BPAC11"},
{"companyName":"Btgp Banco", "symbol":"BPAC3"},
{"companyName":"Btgp Banco", "symbol":"BPAC5"},
{"companyName":"Cambuci", "symbol":"CAMB3"},
{"companyName":"Camil Alimentos S.A.", "symbol":"CAML3"},
{"companyName":"Carrefour Br", "symbol":"CRFB3"},
{"companyName":"CaSAn", "symbol":"CASN"},
{"companyName":"CaSAn", "symbol":"CASN3"},
{"companyName":"CaSAn", "symbol":"CASN4"},
{"companyName":"CCR S.A.", "symbol":"CCRO3"},
{"companyName":"Cea Modas", "symbol":"CEAB3"},
{"companyName":"Ceb", "symbol":"CEBR3"},
{"companyName":"Ceb", "symbol":"CEBR5"},
{"companyName":"Ceb", "symbol":"CEBR6"},
{"companyName":"Cedro", "symbol":"CEDO3"},
{"companyName":"Cedro", "symbol":"CEDO4"},
{"companyName":"Ceee D", "symbol":"CEED3"},
{"companyName":"Ceee D", "symbol":"CEED4"},
{"companyName":"Ceee Gt", "symbol":"EEEL3"},
{"companyName":"Ceee Gt", "symbol":"EEEL4"},
{"companyName":"Ceg", "symbol":"CEGR3"},
{"companyName":"Celesc", "symbol":"CLSC3"},
{"companyName":"Celesc", "symbol":"CLSC4"},
{"companyName":"Celgpar", "symbol":"GPAR3"},
{"companyName":"Celpe", "symbol":"CEPE3"},
{"companyName":"Celpe", "symbol":"CEPE5"},
{"companyName":"Celpe", "symbol":"CEPE6"},
{"companyName":"Cemepe", "symbol":"MAPT3"},
{"companyName":"Cemepe", "symbol":"MAPT4"},
{"companyName":"Centauro", "symbol":"CNTO3"},
{"companyName":"Centrais Elétricas Brasileiras S.A.", "symbol":"Eletrobras"},
{"companyName":"Centrais Elétricas Brasileiras S.A.", "symbol":"Eletrobras"},
{"companyName":"Cesp", "symbol":"CESP3"},
{"companyName":"Cesp", "symbol":"CESP5"},
{"companyName":"Cesp", "symbol":"CESP6"},
{"companyName":"Cia. Hering", "symbol":"HGTX3"},
{"companyName":"Cielo S.A.", "symbol":"CIEL3"},
{"companyName":"Coelba", "symbol":"CEEB3"},
{"companyName":"Coelba", "symbol":"CEEB5"},
{"companyName":"Coelce", "symbol":"COCE3"},
{"companyName":"Coelce", "symbol":"COCE5"},
{"companyName":"Cogna Educação S.A.", "symbol":"COGN3"},
{"companyName":"Comgas", "symbol":"CGAS3"},
{"companyName":"Comgas", "symbol":"CGAS5"},
{"companyName":"Companhia de Locação das Américas", "symbol":"LCAM3"},
{"companyName":"Companhia de Saneamento Básico do Estado de São Paulo", "symbol":"SABESP"},
{"companyName":"Companhia Energética de Minas Gerais", "symbol":"CMIG3"},
{"companyName":"Companhia Energética de Minas Gerais", "symbol":"CMIG4"},
{"companyName":"Companhia Paranaense de Energia", "symbol":"COPEL"},
{"companyName":"Companhia Paranaense de Energia", "symbol":"COPEL"},
{"companyName":"Companhia Siderúrgica Nacional", "symbol":"CSNA3"},
{"companyName":"Const A Lind", "symbol":"CALI3"},
{"companyName":"Const A Lind", "symbol":"CALI4"},
{"companyName":"CopaSA", "symbol":"CSMG3"},
{"companyName":"Copel", "symbol":"CPLE5"},
{"companyName":"Cor Ribeiro", "symbol":"CORR4"},
{"companyName":"CoSAn Log", "symbol":"RLOG3"},
{"companyName":"Cosan S.A.", "symbol":"CSAN3"},
{"companyName":"Cosern", "symbol":"CSRN3"},
{"companyName":"Cosern", "symbol":"CSRN5"},
{"companyName":"Cosern", "symbol":"CSRN6"},
{"companyName":"Coteminas", "symbol":"CTNM3"},
{"companyName":"Coteminas", "symbol":"CTNM4"},
{"companyName":"CPFL Energia S.A.", "symbol":"CPFE3"},
{"companyName":"Cr2", "symbol":"CRDE3"},
{"companyName":"Cristal", "symbol":"CRPG3"},
{"companyName":"Cristal", "symbol":"CRPG5"},
{"companyName":"Cristal", "symbol":"CRPG6"},
{"companyName":"CSHG Logistica", "symbol":"Fundo De Investimento Imobiliario"},
{"companyName":"Csu Cardsyst", "symbol":"CARD3"},
{"companyName":"Cury S/A", "symbol":"CURY3"},
{"companyName":"CVC Brasil Operadora e Agência de Viagens S.A.", "symbol":"CVCB3"},
{"companyName":"Cyre Com Ccp", "symbol":"CCPR3"},
{"companyName":"Cyrela Brazil Realty S.A. Empreendimentos e Participações", "symbol":"CYRE3"},
{"companyName":"D1000 Vfarma", "symbol":"DMVF3"},
{"companyName":"DaSA", "symbol":"DASA3"},
{"companyName":"Dimed", "symbol":"PNVL3"},
{"companyName":"Dimed", "symbol":"PNVL4"},
{"companyName":"Direcional", "symbol":"DIRR3"},
{"companyName":"Dohler", "symbol":"DOHL3"},
{"companyName":"Dohler", "symbol":"DOHL4"},
{"companyName":"Dommo", "symbol":"DMMO3"},
{"companyName":"Dtcom Direct", "symbol":"DTCY3"},
{"companyName":"Duratex", "symbol":"DTEX3"},
{"companyName":"EcoRodovias Infraestrutura e Logística S.A.", "symbol":"ECOR3"},
{"companyName":"EDP", "symbol":"Energias do Brasil S.A."},
{"companyName":"Elektro", "symbol":"EKTR3"},
{"companyName":"Elektro", "symbol":"EKTR4"},
{"companyName":"Eletrobras", "symbol":"ELET5"},
{"companyName":"Eletropar", "symbol":"LIPR3"},
{"companyName":"Emae", "symbol":"EMAE3"},
{"companyName":"Emae", "symbol":"EMAE4"},
{"companyName":"Embraer S.A.", "symbol":"EMBR3"},
{"companyName":"Enauta Part", "symbol":"ENAT3"},
{"companyName":"Encorpar", "symbol":"ECPR3"},
{"companyName":"Encorpar", "symbol":"ECPR4"},
{"companyName":"EnergiSA", "symbol":"ENGI"},
{"companyName":"EnergiSA", "symbol":"ENGI11"},
{"companyName":"EnergiSA", "symbol":"ENGI3"},
{"companyName":"EnergiSA", "symbol":"ENGI4"},
{"companyName":"EnergiSA Mt", "symbol":"ENMT3"},
{"companyName":"EnergiSA Mt", "symbol":"ENMT4"},
{"companyName":"Eneva", "symbol":"ENEV3"},
{"companyName":"Engie Brasil Energia S.A.", "symbol":"EGIE3"},
{"companyName":"Enjoei", "symbol":"ENJU3"},
{"companyName":"Eqtl Para", "symbol":"EQPA3"},
{"companyName":"Eqtl Para", "symbol":"EQPA5"},
{"companyName":"Eqtl Para", "symbol":"EQPA6"},
{"companyName":"Eqtl Para", "symbol":"EQPA7"},
{"companyName":"Equatorial Energia S.A.", "symbol":"EQTL3"},
{"companyName":"Estácio Participações S.A.", "symbol":"YDUQ3"},
{"companyName":"Estapar", "symbol":"ALPK3"},
{"companyName":"Estrela", "symbol":"ESTR3"},
{"companyName":"Estrela", "symbol":"ESTR4"},
{"companyName":"Eternit", "symbol":"ETER3"},
{"companyName":"Eucatex", "symbol":"EUCA3"},
{"companyName":"Eucatex", "symbol":"EUCA4"},
{"companyName":"Even", "symbol":"EVEN3"},
{"companyName":"Excelsior", "symbol":"BAUH4"},
{"companyName":"Eztec", "symbol":"EZTC3"},
{"companyName":"FD Invest Imob Hotel Maxinvest", "symbol":"HTMX11"},
{"companyName":"Fer Heringer", "symbol":"FHER3"},
{"companyName":"FerbaSA", "symbol":"FESA3"},
{"companyName":"FerbaSA", "symbol":"FESA4"},
{"companyName":"Fleury S.A.", "symbol":"FLRY3"},
{"companyName":"Fras Le", "symbol":"FRAS3"},
{"companyName":"Fundo de Investimento Imobiliario", "symbol":"FII Brasil Plural Absoluto Fundo de Fundos"},
{"companyName":"Fundo Investimento Imobiliario Rbr Properties Fii", "symbol":"RBRP11"},
{"companyName":"GafiSA", "symbol":"GFSA3"},
{"companyName":"Generalshopp", "symbol":"GSHP3"},
{"companyName":"Ger Paranap", "symbol":"GEPA3"},
{"companyName":"Ger Paranap", "symbol":"GEPA4"},
{"companyName":"Gerdau Met", "symbol":"GOAU3"},
{"companyName":"Gerdau S.A.", "symbol":"GGBR3"},
{"companyName":"Gerdau S.A.", "symbol":"GGBR4"},
{"companyName":"Gol Linhas Aéreas Inteligentes S.A.", "symbol":"GOLL4"},
{"companyName":"Gp Invest", "symbol":"GPIV33"},
{"companyName":"GPA Companhia Brasileira de Distribuição", "symbol":"PCAR3"},
{"companyName":"Gpc Part", "symbol":"GPCP3"},
{"companyName":"Grazziotin", "symbol":"CGRA3"},
{"companyName":"Grazziotin", "symbol":"CGRA4"},
{"companyName":"Grendene S.A.", "symbol":"GRND3"},
{"companyName":"Grupo Mateus S.A.", "symbol":"GMAT3"},
{"companyName":"Grupo Soma", "symbol":"SOMA3"},
{"companyName":"Guararapes", "symbol":"GUAR3"},
{"companyName":"Habitasul", "symbol":"HBTS5"},
{"companyName":"Haga S/A", "symbol":"HAGA3"},
{"companyName":"Haga S/A", "symbol":"HAGA4"},
{"companyName":"Hapvida", "symbol":"HAPV3"},
{"companyName":"HEDGE Brasil Shopping Fundo de Investimento Imobiliario", "symbol":"HGBS11"},
{"companyName":"Helbor Empreendimentos S.A.", "symbol":"HBOR3"},
{"companyName":"Hercules", "symbol":"HETA3"},
{"companyName":"Hercules", "symbol":"HETA4"},
{"companyName":"Hidrovias", "symbol":"HBSA3"},
{"companyName":"Hoteis Othon", "symbol":"HOOT4"},
{"companyName":"Hypera S.A.", "symbol":"HYPE3"},
{"companyName":"Igb S/A", "symbol":"IGBR3"},
{"companyName":"Iguatemi Empresa de Shopping Centers S.A.", "symbol":"IGTA3"},
{"companyName":"Ihpardini", "symbol":"PARD3"},
{"companyName":"Inds Romi", "symbol":"ROMI3"},
{"companyName":"Indusval", "symbol":"IDVL3"},
{"companyName":"Indusval", "symbol":"IDVL4"},
{"companyName":"Inepar", "symbol":"INEP3"},
{"companyName":"Inepar", "symbol":"INEP4"},
{"companyName":"Intermedica", "symbol":"GNDI3"},
{"companyName":"International Meal Company Alimentacao S.A.", "symbol":"MEAL3"},
{"companyName":"Iochpe", "symbol":"Maxion S.A."},
{"companyName":"Irani", "symbol":"RANI3"},
{"companyName":"Irani", "symbol":"RANI4"},
{"companyName":"IRB", "symbol":"Brasil Resseguros S.A."},
{"companyName":"iShares Ibovespa Fundo de Índice ETF", "symbol":"BOVA11"},
{"companyName":"iShares S&P 500 Fundo de Investimento", "symbol":"Investimento No Exterior"},
{"companyName":"Itaú Unibanco Holding S.A.", "symbol":"ITUB4"},
{"companyName":"Itaú Unibanco Holding S.A.", "symbol":"ITUB3"},
{"companyName":"Itaúsa", "symbol":"Investimentos Itaú S.A."},
{"companyName":"Itausa", "symbol":"Investimentos Itau S.A."},
{"companyName":"J B Duarte", "symbol":"JBDU3"},
{"companyName":"J B Duarte", "symbol":"JBDU4"},
{"companyName":"JBS S.A.", "symbol":"JBSS3"},
{"companyName":"JereisSAti", "symbol":"JPSA3"},
{"companyName":"JHSF Participacoes S.A.", "symbol":"JHSF3"},
{"companyName":"Joao Fortes", "symbol":"JFEN3"},
{"companyName":"JoSApar", "symbol":"JOPA3"},
{"companyName":"JoSApar", "symbol":"JOPA4"},
{"companyName":"Karsten", "symbol":"CTKA3"},
{"companyName":"Karsten", "symbol":"CTKA4"},
{"companyName":"Kepler Weber", "symbol":"KEPL3"},
{"companyName":"Klabin S/A", "symbol":"KLBN3"},
{"companyName":"Klabin S/A", "symbol":"KLBN4"},
{"companyName":"KLABIN S/A UNT N2", "symbol":"KLBN11"},
{"companyName":"Lavvi", "symbol":"LAVV3"},
{"companyName":"Le Lis Blanc", "symbol":"LLIS3"},
{"companyName":"Light S/A", "symbol":"LIGT3"},
{"companyName":"Linx", "symbol":"LINX3"},
{"companyName":"Localiza Rent a Car S.A.", "symbol":"RENT3"},
{"companyName":"Locaweb", "symbol":"LWSA3"},
{"companyName":"Log Com Prop", "symbol":"LOGG3"},
{"companyName":"Log In", "symbol":"LOGN3"},
{"companyName":"Lojas Americ", "symbol":"LAME3"},
{"companyName":"Lojas Americanas S.A.", "symbol":"LAME4"},
{"companyName":"Lojas MariSA", "symbol":"AMAR3"},
{"companyName":"Lojas Renner S.A.", "symbol":"LREN3"},
{"companyName":"Lopes Brasil", "symbol":"LPSB3"},
{"companyName":"Lupatech", "symbol":"LUPA3"},
{"companyName":"M. Dias Branco S.A. Indústria e Comércio de Alimentos", "symbol":"MDIA3"},
{"companyName":"Magazine Luiza S.A.", "symbol":"MGLU3"},
{"companyName":"Mangels Indl", "symbol":"MGEL4"},
{"companyName":"Marcopolo", "symbol":"POMO3"},
{"companyName":"Marcopolo", "symbol":"POMO4"},
{"companyName":"Marfrig Global Foods S.A.", "symbol":"MRFG3"},
{"companyName":"Maxi Renda Fundo De Investimento Imobiliaro", "symbol":"FII"},
{"companyName":"Melhor Sp", "symbol":"MSPA3"},
{"companyName":"Melhor Sp", "symbol":"MSPA4"},
{"companyName":"Meliuz", "symbol":"CASH3"},
{"companyName":"Melnick", "symbol":"MELK3"},
{"companyName":"Merc Brasil", "symbol":"BMEB3"},
{"companyName":"Merc Brasil", "symbol":"BMEB4"},
{"companyName":"Merc Financ", "symbol":"MERC3"},
{"companyName":"Merc Financ", "symbol":"MERC4"},
{"companyName":"Merc Invest", "symbol":"BMIN3"},
{"companyName":"Merc Invest", "symbol":"BMIN4"},
{"companyName":"Merito Desenvolvimento Imobiliario I FII", "symbol":"Fundo de Investimento Imobiliario"},
{"companyName":"Metal Iguacu", "symbol":"MTIG4"},
{"companyName":"Metal Leve", "symbol":"LEVE3"},
{"companyName":"Metalfrio", "symbol":"FRIO3"},
{"companyName":"Metalurgica Gerdau S.A.", "symbol":"GOAU4"},
{"companyName":"MetiSA", "symbol":"MTSA3"},
{"companyName":"MetiSA", "symbol":"MTSA4"},
{"companyName":"Mills Estruturas e Servicos de Engenharia S.A.", "symbol":"MILS3"},
{"companyName":"Minerva", "symbol":"BEEF"},
{"companyName":"Minerva", "symbol":"BEEF3"},
{"companyName":"Minupar", "symbol":"MNPR3"},
{"companyName":"Mitre Realty", "symbol":"MTRE3"},
{"companyName":"Mmx Miner", "symbol":"MMXM11"},
{"companyName":"Mmx Miner", "symbol":"MMXM3"},
{"companyName":"Mont Aranha", "symbol":"MOAR3"},
{"companyName":"Moura Dubeux", "symbol":"MDNE3"},
{"companyName":"Movida Participacoes S.A.", "symbol":"MOVI3"},
{"companyName":"MRV Engenharia e Participações S.A.", "symbol":"MRVE3"},
{"companyName":"Multiplan Empreendimentos Imobiliários S.A.", "symbol":"MULT3"},
{"companyName":"Mundial", "symbol":"MNDL3"},
{"companyName":"Natura &Co Holding S.A.", "symbol":"NTCO3"},
{"companyName":"Natura Cosméticos S.A.", "symbol":"NATU3"},
{"companyName":"Neoenergia", "symbol":"NEOE3"},
{"companyName":"Neogrid", "symbol":"NGRD3"},
{"companyName":"Nord Brasil", "symbol":"BNBR3"},
{"companyName":"Nordon Met", "symbol":"NORD3"},
{"companyName":"Nutriplant", "symbol":"NUTR3"},
{"companyName":"Odontoprev", "symbol":"ODPV3"},
{"companyName":"Oi", "symbol":"OIBR4"},
{"companyName":"Oi S.A.", "symbol":"OIBR3"},
{"companyName":"Omega Ger", "symbol":"OMGE3"},
{"companyName":"Osx Brasil", "symbol":"OSXB3"},
{"companyName":"Ourofino S/A", "symbol":"OFSA3"},
{"companyName":"Padtec", "symbol":"PDTC3"},
{"companyName":"Pague Menos", "symbol":"PGMN3"},
{"companyName":"Panatlantica", "symbol":"PATI3"},
{"companyName":"Panatlantica", "symbol":"PATI4"},
{"companyName":"Par Al Bahia", "symbol":"PEAB3"},
{"companyName":"Par Al Bahia", "symbol":"PEAB4"},
{"companyName":"Paranapanema", "symbol":"PMAM3"},
{"companyName":"Pdg Realt", "symbol":"PDGR3"},
{"companyName":"Pet Center Comércio e Participações S.A.", "symbol":"PETZ3"},
{"companyName":"Pet Manguinh", "symbol":"RPMG3"},
{"companyName":"Petrobras Distribuidora S.A.", "symbol":"BRDT3"},
{"companyName":"Petróleo Brasileiro S.A.", "symbol":"Petrobras"},
{"companyName":"Petróleo Brasileiro S.A.", "symbol":"Petrobras"},
{"companyName":"Petrorio", "symbol":"PRIO3"},
{"companyName":"Pettenati", "symbol":"PTNT3"},
{"companyName":"Pettenati", "symbol":"PTNT4"},
{"companyName":"Pine", "symbol":"PINE4"},
{"companyName":"Planoeplano", "symbol":"PLPL3"},
{"companyName":"Plascar Part", "symbol":"PLAS3"},
{"companyName":"Pomifrutas", "symbol":"FRTA3"},
{"companyName":"Porto Seguro S.A.", "symbol":"PSSA3"},
{"companyName":"Porto Vm", "symbol":"PSVM11"},
{"companyName":"Portobello", "symbol":"PTBL3"},
{"companyName":"Positivo Tec", "symbol":"POSI3"},
{"companyName":"Ppla", "symbol":"PPLA11"},
{"companyName":"Priner", "symbol":"PRNR3"},
{"companyName":"Profarma", "symbol":"PFRM3"},
{"companyName":"Qualicorp Consultoria e Corretora de Seguros S.A.", "symbol":"QUAL3"},
{"companyName":"Quero Quero", "symbol":"LJQQ3"},
{"companyName":"Raia Drogasil S.A.", "symbol":"RADL3"},
{"companyName":"Randon Part", "symbol":"RAPT3"},
{"companyName":"Randon Part", "symbol":"RAPT4"},
{"companyName":"Recrusul", "symbol":"RCSL3"},
{"companyName":"Recrusul", "symbol":"RCSL4"},
{"companyName":"Rede D Or", "symbol":"RDOR3"},
{"companyName":"Rede Energia", "symbol":"REDE3"},
{"companyName":"Renova", "symbol":"RNEW11"},
{"companyName":"Renova", "symbol":"RNEW3"},
{"companyName":"Renova", "symbol":"RNEW4"},
{"companyName":"Riosulense", "symbol":"RSUL4"},
{"companyName":"Rni", "symbol":"RDNI3"},
{"companyName":"Rossi Resid", "symbol":"RSID3"},
{"companyName":"Rumo S.A.", "symbol":"RAIL3"},
{"companyName":"Sanepar", "symbol":"SAPR11"},
{"companyName":"Sanepar", "symbol":"SAPR3"},
{"companyName":"Sanepar", "symbol":"SAPR4"},
{"companyName":"Sansuy", "symbol":"SNSY3"},
{"companyName":"Sansuy", "symbol":"SNSY5"},
{"companyName":"Sansuy", "symbol":"SNSY6"},
{"companyName":"Santander Br", "symbol":"SANB4"},
{"companyName":"Santanense", "symbol":"CTSA3"},
{"companyName":"Santanense", "symbol":"CTSA4"},
{"companyName":"Santos Brp", "symbol":"STBP3"},
{"companyName":"Sao Carlos", "symbol":"SCAR3"},
{"companyName":"Sao Martinho", "symbol":"SMTO3"},
{"companyName":"Saraiva Livr", "symbol":"SLED3"},
{"companyName":"Saraiva Livr", "symbol":"SLED4"},
{"companyName":"Schulz", "symbol":"SHUL4"},
{"companyName":"Seg Al Bahia", "symbol":"CSAB3"},
{"companyName":"Seg Al Bahia", "symbol":"CSAB4"},
{"companyName":"Sequoia Log", "symbol":"SEQL3"},
{"companyName":"Ser Educa", "symbol":"SEER3"},
{"companyName":"Simpar", "symbol":"SIMH3"},
{"companyName":"Sinqia S.A.", "symbol":"SQIA3"},
{"companyName":"Slc Agricola", "symbol":"SLCE3"},
{"companyName":"Smiles Fidelidade S.A.", "symbol":"SMLS3"},
{"companyName":"Sondotecnica", "symbol":"SOND3"},
{"companyName":"Sondotecnica", "symbol":"SOND5"},
{"companyName":"Sondotecnica", "symbol":"SOND6"},
{"companyName":"Springs", "symbol":"SGPS3"},
{"companyName":"Spturis", "symbol":"AHEB3"},
{"companyName":"Spturis", "symbol":"AHEB5"},
{"companyName":"Spturis", "symbol":"AHEB6"},
{"companyName":"Sul America", "symbol":"SULA11"},
{"companyName":"Sul America", "symbol":"SULA3"},
{"companyName":"Sul America", "symbol":"SULA4"},
{"companyName":"Suzano S.A.", "symbol":"SUZB3"},
{"companyName":"TaeSA", "symbol":"TAEE3"},
{"companyName":"TaeSA", "symbol":"TAEE4"},
{"companyName":"Taurus Armas", "symbol":"TASA3"},
{"companyName":"Taurus Armas S.A.", "symbol":"TASA4"},
{"companyName":"Technos", "symbol":"TECN3"},
{"companyName":"Tecnisa S.A.", "symbol":"TCSA3"},
{"companyName":"Tecnosolo", "symbol":"TCNO3"},
{"companyName":"Tecnosolo", "symbol":"TCNO4"},
{"companyName":"Tegma", "symbol":"TGMA3"},
{"companyName":"Teka", "symbol":"TEKA3"},
{"companyName":"Teka", "symbol":"TEKA4"},
{"companyName":"Tekno", "symbol":"TKNO4"},
{"companyName":"Telebras", "symbol":"TELB3"},
{"companyName":"Telebras", "symbol":"TELB4"},
{"companyName":"Telef Brasil", "symbol":"VIVT3"},
{"companyName":"Telefônica Brasil S.A.", "symbol":"VIVT4"},
{"companyName":"Tenda", "symbol":"TEND3"},
{"companyName":"Terra Santa", "symbol":"TESA3"},
{"companyName":"Tex Renaux", "symbol":"TXRX3"},
{"companyName":"TIM S.A.", "symbol":"TIMS3"},
{"companyName":"Time For Fun", "symbol":"SHOW3"},
{"companyName":"TOTVS S.A.", "symbol":"TOTS3"},
{"companyName":"Track Field", "symbol":"TFCO4"},
{"companyName":"Tran Paulist", "symbol":"TRPL3"},
{"companyName":"Tran Paulist", "symbol":"TRPL4"},
{"companyName":"Transmissora Aliança de Energia Elétrica S.A.", "symbol":"TAEE11"},
{"companyName":"TreviSA", "symbol":"LUXM4"},
{"companyName":"Trisul", "symbol":"TRIS3"},
{"companyName":"Triunfo Part", "symbol":"TPIS3"},
{"companyName":"Tupy", "symbol":"TUPY3"},
{"companyName":"Ultrapar Participações S.A.", "symbol":"UGPA3"},
{"companyName":"UnicaSA", "symbol":"UCAS3"},
{"companyName":"Unipar", "symbol":"UNIP3"},
{"companyName":"Unipar", "symbol":"UNIP5"},
{"companyName":"Unipar", "symbol":"UNIP6"},
{"companyName":"Usiminas", "symbol":"USIM3"},
{"companyName":"Usiminas", "symbol":"USIM6"},
{"companyName":"Usinas Siderúrgicas de Minas Gerais S.A.", "symbol":"USIM5"},
{"companyName":"Vale S.A.", "symbol":"VALE3"},
{"companyName":"Valid Solucoes S.A.", "symbol":"VLID3"},
{"companyName":"Via Varejo S.A.", "symbol":"VVAR3"},
{"companyName":"Vinci Logistica Fundo Investimento Imobiliario FII", "symbol":"VILG11"},
{"companyName":"Vivara Participacoes S.A.", "symbol":"VIVA3"},
{"companyName":"Viver", "symbol":"VIVR3"},
{"companyName":"Vulcabras", "symbol":"VULC3"},
{"companyName":"WEG S.A.", "symbol":"WEGE3"},
{"companyName":"Wetzel S/A", "symbol":"MWET3"},
{"companyName":"Wetzel S/A", "symbol":"MWET4"},
{"companyName":"Whirlpool", "symbol":"WHRL3"},
{"companyName":"Whirlpool", "symbol":"WHRL4"},
{"companyName":"Wilson Sons", "symbol":"WSON33"},
{"companyName":"Wiz Solucoes e Corretagem de Seguros S.A.", "symbol":"WIZS3"},
{"companyName":"Wlm Ind Com", "symbol":"WLMM3"},
{"companyName":"Wlm Ind Com", "symbol":"WLMM4"},
];